# coding: utf-8

"""
    anagrafiche

    Servizio Anagrafica RENTRI

    The version of the OpenAPI document: 1.0.20250114-603
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_anagrafiche.models.profili_soggetto import ProfiliSoggetto  # noqa: E501

class TestProfiliSoggetto(unittest.TestCase):
    """ProfiliSoggetto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProfiliSoggetto(self):
        """Test ProfiliSoggetto"""
        # inst = ProfiliSoggetto()

if __name__ == '__main__':
    unittest.main()
