# coding: utf-8

"""
    anagrafiche

    Servizio Anagrafica RENTRI

    The version of the OpenAPI document: 1.0.20250114-603
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_anagrafiche.api.soggetto_delegato_api import SoggettoDelegatoApi


class TestSoggettoDelegatoApi(unittest.TestCase):
    """SoggettoDelegatoApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SoggettoDelegatoApi()

    def tearDown(self) -> None:
        pass

    def test_soggetto_delegato_get(self) -> None:
        """Test case for soggetto_delegato_get

        Elenco dei soggetti delegati
        """
        pass

    def test_soggetto_delegato_num_iscr_ass_registri_get(self) -> None:
        """Test case for soggetto_delegato_num_iscr_ass_registri_get

        Elenco registri
        """
        pass

    def test_soggetto_delegato_num_iscr_ass_siti_get(self) -> None:
        """Test case for soggetto_delegato_num_iscr_ass_siti_get

        Elenco unità locali
        """
        pass

    def test_soggetto_delegato_num_iscr_ass_siti_num_iscr_sito_get(self) -> None:
        """Test case for soggetto_delegato_num_iscr_ass_siti_num_iscr_sito_get

        Ottiene il dettaglio dell'unità locale per cui ha delega il soggetto delegato.
        """
        pass

    def test_soggetto_delegato_registri_identificativo_delete(self) -> None:
        """Test case for soggetto_delegato_registri_identificativo_delete

        Chiudi registro
        """
        pass

    def test_soggetto_delegato_registri_identificativo_get(self) -> None:
        """Test case for soggetto_delegato_registri_identificativo_get

        Dati registro
        """
        pass

    def test_soggetto_delegato_registri_identificativo_put(self) -> None:
        """Test case for soggetto_delegato_registri_identificativo_put

        Modifica registro
        """
        pass

    def test_soggetto_delegato_registri_identificativo_xml_get(self) -> None:
        """Test case for soggetto_delegato_registri_identificativo_xml_get

        Vidimazione virtuale registro in formato XML
        """
        pass

    def test_soggetto_delegato_registri_post(self) -> None:
        """Test case for soggetto_delegato_registri_post

        Apertura nuovo registro
        """
        pass


if __name__ == '__main__':
    unittest.main()
