# coding: utf-8

"""
    anagrafiche

    Servizio Anagrafica RENTRI

    The version of the OpenAPI document: 1.0.20250114-603
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_anagrafiche.models.sito_delega_ass_model import SitoDelegaAssModel  # noqa: E501

class TestSitoDelegaAssModel(unittest.TestCase):
    """SitoDelegaAssModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SitoDelegaAssModel:
        """Test SitoDelegaAssModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SitoDelegaAssModel`
        """
        model = SitoDelegaAssModel()  # noqa: E501
        if include_optional:
            return SitoDelegaAssModel(
                num_iscr_associazione = '',
                stato_delega_ass = 'Attivo',
                data_conferma = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                data_revoca = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                da_associazione = True
            )
        else:
            return SitoDelegaAssModel(
        )
        """

    def testSitoDelegaAssModel(self):
        """Test SitoDelegaAssModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
