# coding: utf-8

"""
    anagrafiche

    Servizio Anagrafica RENTRI

    The version of the OpenAPI document: 1.0.20250114-603
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_anagrafiche.models.aut_albo_categoria_model import AutAlboCategoriaModel

class TestAutAlboCategoriaModel(unittest.TestCase):
    """AutAlboCategoriaModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AutAlboCategoriaModel:
        """Test AutAlboCategoriaModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AutAlboCategoriaModel`
        """
        model = AutAlboCategoriaModel()
        if include_optional:
            return AutAlboCategoriaModel(
                categoria = '',
                classe = '',
                stato = 'Iscritta'
            )
        else:
            return AutAlboCategoriaModel(
        )
        """

    def testAutAlboCategoriaModel(self):
        """Test AutAlboCategoriaModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
