# coding: utf-8

"""
    anagrafiche

    Servizio Anagrafica RENTRI

    The version of the OpenAPI document: 1.0.20250114-603
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_anagrafiche.models.operazioni_recupero_smaltimento import OperazioniRecuperoSmaltimento

class TestOperazioniRecuperoSmaltimento(unittest.TestCase):
    """OperazioniRecuperoSmaltimento unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOperazioniRecuperoSmaltimento(self):
        """Test OperazioniRecuperoSmaltimento"""
        # inst = OperazioniRecuperoSmaltimento()

if __name__ == '__main__':
    unittest.main()
