# coding: utf-8

"""
    anagrafiche

    Servizio Anagrafica RENTRI

    The version of the OpenAPI document: 1.0.20250114-603
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_anagrafiche.models.aut_recer_model import AutRecerModel

class TestAutRecerModel(unittest.TestCase):
    """AutRecerModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AutRecerModel:
        """Test AutRecerModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AutRecerModel`
        """
        model = AutRecerModel()
        if include_optional:
            return AutRecerModel(
                tipo_autorizzazione = 'RecSmalArt208',
                autorizzazione_rif = '',
                data_rilascio = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                data_scadenza = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                attivita_recupero_smaltimento = [
                    'R1'
                    ]
            )
        else:
            return AutRecerModel(
        )
        """

    def testAutRecerModel(self):
        """Test AutRecerModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
