# coding: utf-8

"""
    anagrafiche

    Servizio Anagrafica RENTRI

    The version of the OpenAPI document: 1.0.20250114-603
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_anagrafiche.models.create_registro_request import CreateRegistroRequest

class TestCreateRegistroRequest(unittest.TestCase):
    """CreateRegistroRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateRegistroRequest:
        """Test CreateRegistroRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateRegistroRequest`
        """
        model = CreateRegistroRequest()
        if include_optional:
            return CreateRegistroRequest(
                num_iscr_sito = '0',
                attivita = [
                    'CentroRaccolta'
                    ],
                descrizione = '',
                attivita_rec_smalt = [
                    'R1'
                    ]
            )
        else:
            return CreateRegistroRequest(
                num_iscr_sito = '0',
                attivita = [
                    'CentroRaccolta'
                    ],
        )
        """

    def testCreateRegistroRequest(self):
        """Test CreateRegistroRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
