# coding: utf-8

"""
    anagrafiche

    Servizio Anagrafica RENTRI

    The version of the OpenAPI document: 1.0.20250114-603
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_anagrafiche.models.stati_cat_albo import StatiCatAlbo

class TestStatiCatAlbo(unittest.TestCase):
    """StatiCatAlbo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatiCatAlbo(self):
        """Test StatiCatAlbo"""
        # inst = StatiCatAlbo()

if __name__ == '__main__':
    unittest.main()
