# coding: utf-8

"""
    anagrafiche

    Servizio Anagrafica RENTRI

    The version of the OpenAPI document: 1.0.20250114-603
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_anagrafiche.models.create_registro_soggetto_delegato_request import CreateRegistroSoggettoDelegatoRequest

class TestCreateRegistroSoggettoDelegatoRequest(unittest.TestCase):
    """CreateRegistroSoggettoDelegatoRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateRegistroSoggettoDelegatoRequest:
        """Test CreateRegistroSoggettoDelegatoRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateRegistroSoggettoDelegatoRequest`
        """
        model = CreateRegistroSoggettoDelegatoRequest()
        if include_optional:
            return CreateRegistroSoggettoDelegatoRequest(
                num_iscr_sito = '0',
                num_iscr_ass = '0',
                descrizione = '0'
            )
        else:
            return CreateRegistroSoggettoDelegatoRequest(
                num_iscr_sito = '0',
                num_iscr_ass = '0',
                descrizione = '0',
        )
        """

    def testCreateRegistroSoggettoDelegatoRequest(self):
        """Test CreateRegistroSoggettoDelegatoRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
