# coding: utf-8

"""
    anagrafiche

    Servizio Anagrafica RENTRI

    The version of the OpenAPI document: 1.0.20250114-603
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from rentri_anagrafiche.models.operatore_model import OperatoreModel  # noqa: E501

class TestOperatoreModel(unittest.TestCase):
    """OperatoreModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OperatoreModel:
        """Test OperatoreModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OperatoreModel`
        """
        model = OperatoreModel()  # noqa: E501
        if include_optional:
            return OperatoreModel(
                num_iscr = '',
                profilo_soggetto = 'Impresa',
                data_iscrizione = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                identificativo = '',
                ipa = '',
                denominazione = '',
                forma_giuridica_id = '',
                piva = '',
                cciaarea = '',
                nrea = '',
                data_iscrizione_ri = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                stato_impresa_ri = '',
                dipendenti_ri = 56,
                data_rilevazione_dipendenti_ri = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                nazione_slid = '',
                provincia_slid = '',
                comune_slid = '',
                citta_sl = '',
                indirizzo_sl = '',
                civico_sl = '',
                capsl = '',
                pec = '',
                cod_fisc_lr = '',
                cognome_lr = '',
                nome_lr = '',
                dipendenti = 56,
                data_ultima_visura = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                flag_esonerato_iscr_albo = 56
            )
        else:
            return OperatoreModel(
        )
        """

    def testOperatoreModel(self):
        """Test OperatoreModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
