# coding: utf-8

"""
    anagrafiche

    Servizio Anagrafica RENTRI

    The version of the OpenAPI document: 1.0.20250114-603
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from rentri_anagrafiche.models.aut_albo_model import AutAlboModel

class TestAutAlboModel(unittest.TestCase):
    """AutAlboModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AutAlboModel:
        """Test AutAlboModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AutAlboModel`
        """
        model = AutAlboModel()
        if include_optional:
            return AutAlboModel(
                sezione = '',
                numero_iscrizione = 56,
                attiva = True,
                data_iscrizione = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                categorie = [
                    rentri_anagrafiche.models.aut_albo_categoria_model.AutAlboCategoriaModel(
                        categoria = '', 
                        classe = '', 
                        stato = null, )
                    ]
            )
        else:
            return AutAlboModel(
        )
        """

    def testAutAlboModel(self):
        """Test AutAlboModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
