# coding: utf-8

"""
    anagrafiche

    Servizio Anagrafica RENTRI

    The version of the OpenAPI document: 1.0.20250114-603
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class Attivita(str, Enum):
    """
    Attivita
    """

    """
    allowed enum values
    """
    CENTRORACCOLTA = 'CentroRaccolta'
    PRODUZIONE = 'Produzione'
    RECUPERO = 'Recupero'
    SMALTIMENTO = 'Smaltimento'
    TRASPORTO = 'Trasporto'
    INTERMEDIAZIONESENZADETENZIONE = 'IntermediazioneSenzaDetenzione'

    @classmethod
    def from_json(cls, json_str: str) -> Attivita:
        """Create an instance of Attivita from a JSON string"""
        return Attivita(json.loads(json_str))


