# coding: utf-8

"""
    anagrafiche

    Servizio Anagrafica RENTRI

    The version of the OpenAPI document: 1.0.20250114-603
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class ProfiliSoggetto(str, Enum):
    """
    ProfiliSoggetto
    """

    """
    allowed enum values
    """
    IMPRESA = 'Impresa'
    ENTE = 'Ente'
    ALTRO = 'Altro'
    ASSOCIAZIONECATEGORIA = 'AssociazioneCategoria'
    AMMINISTRAZIONE = 'Amministrazione'

    @classmethod
    def from_json(cls, json_str: str) -> ProfiliSoggetto:
        """Create an instance of ProfiliSoggetto from a JSON string"""
        return ProfiliSoggetto(json.loads(json_str))


