# coding: utf-8

"""
    anagrafiche

    Servizio Anagrafica RENTRI

    The version of the OpenAPI document: 1.0.20250114-603
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from rentri_anagrafiche.models.stati import Stati
from typing import Optional, Set
from typing_extensions import Self

class SitoDelegaAssModel(BaseModel):
    """
    Stato delega soggetto delegato
    """ # noqa: E501
    num_iscr_associazione: Optional[StrictStr] = None
    stato_delega_ass: Optional[Stati] = None
    data_conferma: Optional[datetime] = None
    data_revoca: Optional[datetime] = None
    da_associazione: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["num_iscr_associazione", "stato_delega_ass", "data_conferma", "data_revoca", "da_associazione"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SitoDelegaAssModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if num_iscr_associazione (nullable) is None
        # and model_fields_set contains the field
        if self.num_iscr_associazione is None and "num_iscr_associazione" in self.model_fields_set:
            _dict['num_iscr_associazione'] = None

        # set to None if data_conferma (nullable) is None
        # and model_fields_set contains the field
        if self.data_conferma is None and "data_conferma" in self.model_fields_set:
            _dict['data_conferma'] = None

        # set to None if data_revoca (nullable) is None
        # and model_fields_set contains the field
        if self.data_revoca is None and "data_revoca" in self.model_fields_set:
            _dict['data_revoca'] = None

        # set to None if da_associazione (nullable) is None
        # and model_fields_set contains the field
        if self.da_associazione is None and "da_associazione" in self.model_fields_set:
            _dict['da_associazione'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SitoDelegaAssModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "num_iscr_associazione": obj.get("num_iscr_associazione"),
            "stato_delega_ass": obj.get("stato_delega_ass"),
            "data_conferma": obj.get("data_conferma"),
            "data_revoca": obj.get("data_revoca"),
            "da_associazione": obj.get("da_associazione")
        })
        return _obj


