# coding: utf-8

"""
    anagrafiche

    Servizio Anagrafica RENTRI

    The version of the OpenAPI document: 1.0.20250114-603
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class Stati(str, Enum):
    """
    Stati
    """

    """
    allowed enum values
    """
    ATTIVO = 'Attivo'
    ELIMINATO = 'Eliminato'
    SOSPESO = 'Sospeso'
    CHIUSO = 'Chiuso'
    DACONFERMARE = 'DaConfermare'

    @classmethod
    def from_json(cls, json_str: str) -> Stati:
        """Create an instance of Stati from a JSON string"""
        return Stati(json.loads(json_str))


