# coding: utf-8

"""
    anagrafiche

    Servizio Anagrafica RENTRI

    The version of the OpenAPI document: 1.0.20250114-603
    Contact: techref@rentri.it
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class TipiAutorizzazione(str, Enum):
    """
    TipiAutorizzazione
    """

    """
    allowed enum values
    """
    RECSMALART208 = 'RecSmalArt208'
    RECSMALIMPMOBILIART208 = 'RecSmalImpMobiliArt208'
    RICERCASPERIMENTAZIONE = 'RicercaSperimentazione'
    AIA = 'AIA'
    RECPROCSEMPLIFICATA = 'RecProcSemplificata'
    OPBONIFICA = 'OpBonifica'
    STRAORDINARIO = 'Straordinario'
    COMTRATTAMENTOACQUEREFLUE = 'ComTrattamentoAcqueReflue'
    AUTTRATTAMENTOACQUEREFLUE = 'AutTrattamentoAcqueReflue'

    @classmethod
    def from_json(cls, json_str: str) -> TipiAutorizzazione:
        """Create an instance of TipiAutorizzazione from a JSON string"""
        return TipiAutorizzazione(json.loads(json_str))


